services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: spring-containers-app:stable
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    restart: unless-stopped
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
  redis:
    image: redis:latest
    restart: unless-stopped
