FROM amazoncorretto:17-alpine AS build
WORKDIR /app
COPY . /app
RUN chmod +x ./mvnw && ./mvnw clean package -DskipTests

FROM amazoncorretto:17-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "./app.jar"]